- hosts: webapp
  become: yes
  vars:
  tasks:
    - name: install python libraries use pip
      pip:
        requirements: "{{ wsgi_app_basedir }}/{{ app_name }}/requirements.txt"
        state: present
        executable: "{{ webapp_pip_ver }}"
