- hosts: webapp
  become: yes
  vars:
  tasks:
    - name: install webserver
      apt:
        pkg:
          - apache2
          - libapache2-mod-wsgi-py3
    - name: install web application server
      apt:
        pkg:
          - python3
          - python3-dev
          - python3-setuptools
          - python3-pip
          - default-libmysqlclient-dev
          - gcc
          - make
          - git
    - name: restart apache
      service: name={{ httpd_name }} state=restarted
