- hosts: webapp
  become: yes
  vars:
    httpd_mods:
      - wsgi
      - expires
  tasks:
    - name: copy logrotate config file
      become_user: "{{ ansible_ssh_user }}"
      synchronize:
        src: "etc/logrotate.d/"
        dest: "/etc/logrotate.d/"
        recursive: yes
    - name: chown logrotate config files
      file:
        path: "/etc/logrotate.d/"
        owner: "root"
        group: "root"
        recurse: yes
    - name: copy httpd config files (/etc/apache2 direct)
      become_user: "{{ ansible_ssh_user }}"
      synchronize:
        src: "etc/apache2/"
        dest: "{{ httpd_conf_dir }}"
        recursive: no
    - name: chown httpd config files
      file:
        path: "{{ httpd_conf_dir }}"
        owner: "root"
        group: "root"
        recurse: yes
    - name: enable apache2 modules
      command: a2enmod "{{ item }}"
      with_items: "{{ httpd_mods }}"
