- hosts: webappdb
  become: yes
  vars:
  tasks:
    - name: install database server
      yum:
        name: "{{ packages }}"
        update_cache: yes
        state: installed
      vars:
        packages:
        - mariadb-server
